export const ROUTES ={
    HOME:"/",
    AUTH:"/login",
    ADDNEW:"addnew",
    SHOWALL :"/showall",
    EDITAPP :"/editpassword",
    VIEWAPP :"/viewpassword",
    PROFILE :"/profile",
    SETTING:"/setting",
    USERS:"/users",
    INVITATION:"/join",
    VIEWCOMPANY:"/companyregistration",
    ADDNEWUSER:"/addnewuser",
    COMPANYREGISTER:"/companyregistration",
    COMPANYREGISTRATIONFORM:"/CompanyRegistrationForm",
}